version: "3"

services:
  app:
    image: php-simple:dev
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        PHP_VERSION: '${PHP_VERSION:-8.1.18}'
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - 127.0.0.1:${PORT}:8000
    entrypoint: php -S 0.0.0.0:8000 -t .
    #entrypoint: sleep infinitely
