version: "3"

services:
  app:
    image: google85/php-fpm:${DOCKER_IMAGE_TAG}
    container_name: php-simple
    environment:
      PORT: '${PORT}'
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - 127.0.0.1:${PORT}:8000
    entrypoint: php -S 0.0.0.0:8000 -t .
