version: "3"

services:
  app:
    image: php-simple:dev
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.1.18
        PORT: ${PORT_INT}
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - 127.0.0.1:${PORT}:${PORT_INT}
    entrypoint: php -S 0.0.0.0:${PORT_INT} -t .
    #entrypoint: sleep infinitely
